### ISSUE TITLE
Homebrew thinks localstack-cli version is `64`

### ISSUE THREAD

**Issue by mcous** [localstack/homebrew-tap#3]
Hello! There's an issue with the formula that caused me to become stuck on an old version of the localstack-cli.

In the absence of an explicitly specified version, Homebrew tries to infer the version from the asset URL. Unfortunately, this logic is quite naive, and the asset URLs for `localstack-cli` include the architecture (e.g. `localstack-cli-3.5.0-darwin-arm64.tar.gz`).

This causes Homebrew to think the version is `64`

```shell
❯ brew info localstack-cli
==> localstack/tap/localstack-cli: stable 64
Localstack cli packaged using pyinstaller
https://github.com/localstack/localstack-cli
Installed
/opt/homebrew/Cellar/localstack-cli/64 (961 files, 50.9MB) *
  Built from source on 2024-06-27 at 15:21:57
From: https://github.com/localstack/homebrew-tap/blob/HEAD/Formula/localstack-cli.rb
License: NOASSERTION
```

**Comment by mcous** [comment]
Related: https://github.com/Justintime50/homebrew-releaser/issues/39

**Comment by alexrashed** [comment]
Thanks a lot for the pointer, @mcous!
I explicitly set the version for the current release of the tap with https://github.com/localstack/homebrew-tap/commit/be50f9598b57ac12412cc039d5b0c8ebca673092.
I also created https://github.com/localstack/localstack-cli/pull/26, and this should fix the upcoming releases of LocalStack (the next one being scheduled for end of July).

**Comment by mcous** [comment]
Thank you!
